<h1 align="center" style="color:blue";><b>Machine Learning Models</b></h1>

<h1 style="color:red";> 1.Linear Regression:</h1>

<p><b> Linear regression is one of the easiest and most popular Machine Learning algorithms. It is a statistical method that is used for predictive analysis. Linear regression makes predictions for continuous/real or numeric variables such as sales, salary, age, product price, etc.</p>

<p><b>Linear regression algorithm shows a linear relationship between a dependent (y) and one or more independent (y) variables, hence called as linear regression. Since linear regression shows the linear relationship, which means it finds how the value of the dependent variable is changing according to the value of the independent variable.</p>

<img src="linear-regression-in-machine-learning.png"/>

<h5><b> Mathematically:</b></h5>

<b>y= a0+a1x+ ε</b><br>
Here,

Y= Dependent Variable (Target Variable)<br>
X= Independent Variable (predictor Variable)<br>
a0= intercept of the line (Gives an additional degree of freedom)<br>
a1 = Linear regression coefficient (scale factor to each input value).<br>
ε = random error<br>

The values for x and y variables are training datasets for Linear Regression model representation.

<h2>Types of Linear Regression:</h3>

<b>1.Simple Linear Regression:</b><br>
If a single independent variable is used to predict the value of a numerical dependent variable, then such a Linear Regression algorithm is called Simple Linear Regression.
<br>
<b>2.Multiple Linear regression:</b><br>
If more than one independent variable is used to predict the value of a numerical dependent variable, then such a Linear Regression algorithm is called Multiple Linear Regression.

<h2>Finding the best fit line:</h2>

<p>When working with linear regression, our main goal is to find the best fit line that means the error between predicted values and actual values should be minimized. The best fit line will have the least error.<br>

The different values for weights or the coefficient of lines (a0, a1) gives a different line of regression, so we need to calculate the best values for a0 and a1 to find the best fit line, so to calculate this we use cost function.</p>

<h3>Cost function-</h3>

<ul>
    <li>The different values for weights or coefficient of lines (a0, a1) gives the different line of regression, and the cost function is used to estimate the values of the coefficient for the best fit line.</li>
    <li>Cost function optimizes the regression coefficients or weights. It measures how a linear regression model is performing.</li>
    <li>We can use the cost function to find the accuracy of the <b>mapping function</b>, which maps the input variable to the output variable. This mapping function is also known as <b>Hypothesis function</b>.</li>
    
</ul>

<b>For Linear Regression, we use the Mean Squared Error (MSE) cost function, which is the average of squared error occurred between the predicted values and actual values. It can be written as:</b>

<img src="linear-regression-in-machine-learning4.png"/>

<b>Where,</b>
<br>
N=Total number of observation<br>
Yi = Actual value<br>
(a1xi+a0)= Predicted value.<br>
<br>
<b>Residuals:</b> The distance between the actual value and predicted values is called residual. If the observed points are far from the regression line, then the residual will be high, and so cost function will high. If the scatter points are close to the regression line, then the residual will be small and hence the cost function.

<h3>Model Performance:<h3>

<p>The Goodness of fit determines how the line of regression fits the set of observations. The process of finding the best model out of various models is called <b>optimization</b>. It can be achieved by below method:</p>

<h3>1. R-squared method:</h3>

<li>R-squared is a statistical method that determines the goodness of fit.</li>
<li>It measures the strength of the relationship between the dependent and independent variables on a scale of 0-100%.
The high value of R-square determines the less difference between the predicted values and actual values and hence represents a good model.</li>
<li>It is also called a coefficient of determination, or coefficient of multiple determination for multiple regression.</li>
<br>
It can be calculated from the below formula:
<img src="linear-regression-in-machine-learning5.png"/>

<h1 align="center" style="color:green";>Python Implementation of Linear Regression</h1>

<h3>Import Libraries requried:</h3>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

<h3>Import Dataset:

In [5]:
data = pd.read_csv("data_house_price.csv")

In [6]:
data.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [7]:
data.shape

(4600, 18)

In [9]:
data.describe()

price     bedrooms    bathrooms   sqft_living      sqft_lot  \
count  4.600000e+03  4600.000000  4600.000000   4600.000000  4.600000e+03   
mean   5.519630e+05     3.400870     2.160815   2139.346957  1.485252e+04   
std    5.638347e+05     0.908848     0.783781    963.206916  3.588444e+04   
min    0.000000e+00     0.000000     0.000000    370.000000  6.380000e+02   
25%    3.228750e+05     3.000000     1.750000   1460.000000  5.000750e+03   
50%    4.609435e+05     3.000000     2.250000   1980.000000  7.683000e+03   
75%    6.549625e+05     4.000000     2.500000   2620.000000  1.100125e+04   
max    2.659000e+07     9.000000     8.000000  13540.000000  1.074218e+06   

            floors   waterfront         view    condition   sqft_above  \
count  4600.000000  4600.000000  4600.000000  4600.000000  4600.000000   
mean      1.512065     0.007174     0.240652     3.451739  1827.265435   
std       0.538288     0.084404     0.778405     0.677230   862.168977   
min       1.000000     0.000000     0.000000     1.000000   370.000000   
25%       1.000000     0.000000     0.000000     3.000000  1190.000000   
50%       1.500000     0.000000     0.000000     3.000000  1590.000000   
75%       2.000000     0.000000     0.000000     4.000000  2300.000000   
max       3.500000     1.000000     4.000000     5.000000  9410.000000   

       sqft_basement     yr_built  yr_renovated  
count    4600.000000  4600.000000   4600.000000  
mean      312.081522  1970.786304    808.608261  
std       464.137228    29.731848    979.414536  
min         0.000000  1900.000000      0.000000  
25%         0.000000  1951.000000      0.000000  
50%         0.000000  1976.000000      0.000000  
75%       610.000000  1997.000000   1999.000000  
max      4820.000000  2014.000000   2014.000000

In [11]:
data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [22]:
X = data[['bedrooms','bathrooms','sqft_living']]
y = data[['price']]

In [23]:
X.head()

bedrooms  bathrooms  sqft_living
0       3.0       1.50         1340
1       5.0       2.50         3650
2       3.0       2.00         1930
3       3.0       2.25         2000
4       4.0       2.50         1940

In [24]:
y.head()

price
0   313000.0
1  2384000.0
2   342000.0
3   420000.0
4   550000.0

In [30]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [31]:
model

LinearRegression()

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [34]:
X_train.shape

(3220, 3)

In [36]:
X_test.shape

(1380, 3)

In [37]:
y_train.shape

(3220, 1)

In [38]:
y_test.shape

(1380, 1)

In [39]:
model.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = model.predict(X_test)

array([[266186.79092365],
       [312401.99687976],
       [536107.57262829],
       ...,
       [504771.1596182 ],
       [938696.06349972],
       [467698.1331503 ]])

In [46]:
x_pred = model.predict(X_train)

In [47]:
x_pred

array([[840611.0526025 ],
       [396214.9222849 ],
       [530261.94368104],
       ...,
       [664615.62707943],
       [434451.09837916],
       [342684.27575293]])

In [73]:
model.score(X_test,y_pred)

1.0

In [63]:
model.predict([[3,1,1340]])

d:\Users\e3t\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[335343.70253632]])

In [64]:
model.predict([[5,3,2500]])

d:\Users\e3t\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[590801.36878663]])

In [66]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [69]:
# for Contineous vale 'accuracy_score','confusion_matrix' can't be find

In [119]:
model.intercept_

1.4551915228366852e-11

In [120]:
model.coef_

array([1.])